# Generated by Django 3.2 on 2022-01-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVideo', '0002_auto_20211230_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamvideo',
            name='videoURL',
            field=models.URLField(null=True, verbose_name='Video url'),
        ),
    ]
