# Generated by Django 3.2 on 2022-01-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVideo', '0003_alter_streamvideo_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamvideo',
            name='videoURL',
            field=models.URLField(blank=True, null=True, verbose_name='Video url'),
        ),
    ]
